import React, {Component } from 'react'
import Gallery from 'react-photo-gallery'
import Lightbox from 'react-images'

const photos = [
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4092.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4093.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4094.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4095.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4096.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4097.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4098.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4099.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4100.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4101.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4102.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4103.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4104.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4105.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4106.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4107.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4108.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4109.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4110.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4111.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4112.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4113.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4114.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4115.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4116.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4117.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4118.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4119.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4120.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4121.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4122.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4123.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4124.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4125.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4126.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4127.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4128.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4129.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4130.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4131.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4132.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4133.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4134.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4135.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4136.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4137.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4138.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4139.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4140.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4141.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4142.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4143.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4144.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4145.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4146.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4147.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4148.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4149.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4150.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4151.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4153.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4154.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4155.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4156.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4157.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4158.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4159.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4160.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4161.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4162.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4163.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4164.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4165.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4166.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4167.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4168.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4169.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4170.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4171.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4172.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4173.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4174.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4175.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4176.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4177.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4178.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4179.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4180.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4181.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4182.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4183.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4184.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4185.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4186.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4187.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4188.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4189.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4190.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4191.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4192.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4193.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4194.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4195.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4196.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4197.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4198.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4199.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4200.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4201.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4202.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4203.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4204.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4205.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4206.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4207.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4208.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4209.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4210.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4211.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4212.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4213.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4214.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4215.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4216.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4217.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4218.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4219.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4220.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4221.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4222.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4223.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4224.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4225.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4226.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4227.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4228.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4229.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4230.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4231.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4232.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4233.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4234.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4235.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4236.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4237.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4238.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4239.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4240.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4241.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4242.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4243.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4244.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4245.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4246.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4247.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4248.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4249.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4250.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4251.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4252.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4253.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4254.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4255.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4256.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4257.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4258.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4259.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4260.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4261.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4262.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4263.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4264.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4265.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4266.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4267.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4268.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4269.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4270.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4271.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4272.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4273.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4274.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4275.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4276.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4277.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4278.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4279.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4280.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4281.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4282.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4283.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4284.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4285.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4286.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4287.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4288.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4289.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4290.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4291.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4292.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4293.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4294.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4295.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4296.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4297.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4298.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4299.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4300.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4301.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4302.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4303.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4304.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4305.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4306.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4307.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4308.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4309.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4310.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4311.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4312.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4313.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4314.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4315.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4316.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4317.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4318.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4319.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4320.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4321.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4322.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4323.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4324.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4325.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4326.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4327.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4328.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4329.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4330.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4331.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4332.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4334.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4335.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4337.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4338.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4339.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4340.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4341.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4342.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4343.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4344.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4345.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4346.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4347.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4348.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4349.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4350.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4351.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4352.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4353.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4355.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4356.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4357.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4358.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4359.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4360.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4361.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4362.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4363.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4364.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4365.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4366.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4367.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4368.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4370.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4373.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4374.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4375.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4376.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4377.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4378.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4379.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4380.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4381.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4382.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4383.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4384.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4385.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4386.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4387.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4388.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4389.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4390.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4391.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4392.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4393.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4394.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4395.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4396.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4397.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4398.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4399.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4400.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4401.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4402.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4403.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4406.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4407.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4408.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4409.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4410.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4411.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4412.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4413.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4414.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4415.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4416.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4417.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4418.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4419.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4420.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4421.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4422.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4423.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4424.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4425.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4426.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4427.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4428.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4429.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4430.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4431.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4432.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4433.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4434.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4435.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4436.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4437.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4438.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4439.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4440.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4443.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4444.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4445.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4446.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4447.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4448.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4449.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4450.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4451.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4452.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4453.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4454.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4455.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4456.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4457.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4458.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4459.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4460.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4461.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4462.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4463.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4464.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4465.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4466.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4467.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4468.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4469.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4470.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4471.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4472.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4473.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4474.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4476.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4477.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4479.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4480.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4481.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4482.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4483.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4484.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4485.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4486.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4487.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4488.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4489.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4490.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4491.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4492.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4493.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4494.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4495.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4496.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4498.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4499.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4500.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4501.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4502.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4503.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4504.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4505.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4506.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4507.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4508.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4509.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4510.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4519.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4520.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4521.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4522.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4523.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4524.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4525.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4526.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4527.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4528.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4529.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4530.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4531.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4532.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4533.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4534.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4535.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4536.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4537.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4538.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4539.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4540.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4541.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4542.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4543.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4544.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4545.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4546.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4547.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4548.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4549.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4550.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4551.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4552.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4553.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4554.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4555.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4556.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4557.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4558.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4559.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4560.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4561.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4562.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4563.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4564.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4565.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4566.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4567.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4568.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4569.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4570.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4571.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4572.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4573.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4574.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4575.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4576.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4577.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4579.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4580.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4581.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4582.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4583.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4584.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4586.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4587.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4588.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4589.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4590.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4591.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4592.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4593.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4594.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4595.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4596.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4597.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4598.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4599.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4605.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4606.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4607.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4608.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4609.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4610.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4611.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4612.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4613.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4614.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4615.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4616.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4617.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4618.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4619.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4620.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4621.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4622.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4623.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4624.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4625.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4626.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4627.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4628.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4629.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4630.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4631.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4632.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4634.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4635.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4640.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4641.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4642.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4643.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4644.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4645.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4646.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4647.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4648.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4649.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4650.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4651.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4652.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4657.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4658.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4659.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4660.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4664.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4665.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4666.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4667.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4668.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4669.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4670.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4671.jpg', width: 2, height: 3 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4672.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4673.jpg', width: 3, height: 2 },
  { src: 'https://ceverett-io.nyc3.digitaloceanspaces.com/IMG_4674.jpg', width: 3, height: 2 }
]

export default class PhotoGallery extends Component {

  constructor(){
    super()
    this.state = {
      photos: photos,
      currentImage: 0
    }
    this.closeLightbox = this.closeLightbox.bind(this);
    this.openLightbox = this.openLightbox.bind(this);
    this.gotoNext = this.gotoNext.bind(this);
    this.gotoPrevious = this.gotoPrevious.bind(this);
  }

  openLightbox(event, obj) {
    this.setState({
      currentImage: obj.index,
      lightboxIsOpen: true,
    });
  }

  closeLightbox() {
    this.setState({
      currentImage: 0,
      lightboxIsOpen: false,
    });
  }

  gotoPrevious() {
    this.setState({
      currentImage: this.state.currentImage - 1,
    });
  }

  gotoNext() {
    this.setState({
      currentImage: this.state.currentImage + 1,
    });
  }

  render() {
    return (
      <div className="gallery">
        <Gallery photos={photos} onClick={this.openLightbox}/>
        <Lightbox images={photos}
          onClose={this.closeLightbox}
          onClickPrev={this.gotoPrevious}
          onClickNext={this.gotoNext}
          currentImage={this.state.currentImage}
          isOpen={this.state.lightboxIsOpen}
        />
      </div>
    )
  }

}
